Create and merge array from (multi-valued) attributes
nextcloud/user_saml pull request #307
Opened 2019-02-16 09:21 UTC by mrvanes

When consuming attributes from headers instead of env, multi-valued attributes are sometimes header name postfixed (_01, _02) or merged using a separator. The prior can not easily be solved without extra logic, but the latter can be exploded using the separator character. The advantage is that everything will now be cast into an array, so that values can always be array_merged. Even multi separator-merged-multi-valued attributes will result in the correct multi-valued value this way.

This will solve https://github.com/nextcloud/user_saml/issues/293

TODO: I lack the time and Nextcloud app development experience to introduce a seperator setting in UI.
Please add one before merging this PR.

2019-03-12 22:52 UTC, tuxcrafter commented
What lines can I add to the code to print some debug information.

My saml is passing an array of groups, but I only get one group in my user preferences?

```
[Tue Mar 12 23:45:11.871725 2019] [:error] [pid 3848] [12/Mar/2019:23:45:11]  DEBUG(ipsilon/providers/common.py:93 Redirect.debug()): saml2: jelledj's attributes: {'_groups': ['generalinformation', 'communications'], 'surname': 'de Jong', '_extras': {'sssd': {}}, 'groups': ['generalinformation', 'communications'], '_auth_type': 'password', 'givenname': 'Jelle', 'email': 'jelledejong@somewhere.nl'}
[Tue Mar 12 23:45:11.873282 2019] [:error] [pid 3848] [12/Mar/2019:23:45:11]  DEBUG(ipsilon/providers/common.py:93 Redirect.debug()): saml2: value de Jong
[Tue Mar 12 23:45:11.874799 2019] [:error] [pid 3848] [12/Mar/2019:23:45:11]  DEBUG(ipsilon/providers/common.py:93 Redirect.debug()): saml2: value generalinformation
[Tue Mar 12 23:45:11.876352 2019] [:error] [pid 3848] [12/Mar/2019:23:45:11]  DEBUG(ipsilon/providers/common.py:93 Redirect.debug()): saml2: value communications
[Tue Mar 12 23:45:11.877856 2019] [:error] [pid 3848] [12/Mar/2019:23:45:11]  DEBUG(ipsilon/providers/common.py:93 Redirect.debug()): saml2: value Jelle
[Tue Mar 12 23:45:11.879394 2019] [:error] [pid 3848] [12/Mar/2019:23:45:11]  DEBUG(ipsilon/providers/common.py:93 Redirect.debug()): saml2: value jelledejong@somewhere.nl
```

2025-05-06 15:38 UTC, blizzz requested changes
I am going through the open PRs and a there is a bunch of dusty ones here 😅

Now the behaviour is quite different though and no callees of that method are adjusted. When dealing with different formats we should also have a set of unit tests for them.

2025-05-06 15:56 UTC, mrvanes commented
This is so old I don't even have a requirement for it anymore, but to answer the question: the behaviour never changed so that any caller was confused. The change just resulted in a more consistent representation of multi-valued attributes. Back then, the change correctly let me supply multi-valued attributes as semi-column separated strings and then profit...

2025-05-06 18:00 UTC, blizzz commented
> This is so old I don't even have a requirement for it anymore

Yeah, sorry about that. 

Maybe  I am missing some, but back then only a string was returned. But maybe that was the misbehaviour. Maybe the callees changed since; need to give it a more thorough look. 

Nevertheless, thanks for the PR and for the responsivity.

2025-05-13 11:08 UTC, blizzz commented
Replacing this with a slightly different approach in #954. The logic was present elsewhere where built-in SAML mode was not affected.

2025-05-13 11:08 UTC, closed without merging