Switch section titles to H2
nextcloud/user_saml pull request #602
Opened 2022-04-15 10:10 UTC by solracsf

After
![image](https://user-images.githubusercontent.com/12234510/163558575-68b65c9e-ba3b-45ec-84ef-36c95b48e6bc.png)

Before
![image](https://user-images.githubusercontent.com/12234510/163558620-b4520a49-f728-48e3-8a66-35d9ea72861f.png)

2022-05-09 13:46 UTC, CarlSchwan approved these changes

2022-05-24 09:36 UTC, blizzz requested changes
h2 is already used for "SSO & SAML authentication", following sections are hierarchically belonging to it, aren't on the same level.

2022-05-24 12:08 UTC, solracsf commented
Yeah, this is a global `h3` style problem, this is just a quick (yet dirty) fix.
If someone wants to fix it globally, no problem :)

2023-04-24 17:37 UTC, closed without merging

2023-05-31 12:24 UTC, solracsf commented
Fixed by https://github.com/nextcloud/user_saml/pull/730