Fix displaying of global checkboxes in user_saml settings
nextcloud/user_saml pull request #613
Opened 2022-05-11 13:52 UTC by KoffeinKaio

Partly fix problems lined out in #573 
Templated wanted the values in config array, config array is only idp settings from user_saml, not the global ones.
Hope this approach is ok.

2022-05-18 12:17 UTC, CarlSchwan commented on lib/Settings/Admin.php
> +                        ];
```suggestion
				'text' => $this->l10n->t('Only allow authentication if an account exists on some other backend (e.g. LDAP).', [$this->defaults->getName()]),
				type' => 'checkbox',
				'global' => true,
				'value' => $this->config->getAppValue('user_saml', 'general-require_provisioned_account', 0)
			];
```

tab vs space ;)

2022-05-24 09:39 UTC, blizzz requested changes
there is something wrong with this PR.  Certainly the change in l10n should not be here.

2022-05-24 09:41 UTC, KoffeinKaio commented
ah heck, I made a mistake by rebasing. I instead merged all new commits into my repo. lemme think about how to fix this

2022-05-24 09:59 UTC, blizzz commented on lib/Settings/Admin.php
> +				type' => 'checkbox',
```suggestion
				'type' => 'checkbox',
```

2022-05-24 10:03 UTC, KoffeinKaio commented
aw to hell with that. lemme fix this again

2022-05-24 10:29 UTC, blizzz commented
@KoffeinKaio i took the freedom to rebase, drop the unneeded commits and amend the missing single quote fix to your main commit

2022-05-24 10:30 UTC, KoffeinKaio commented
> @KoffeinKaio i took the freedom to rebase, drop the unneeded commits and amend the missing single quote fix to your main commit

thanks, dont PR and work on other things my kids

2022-05-24 11:10 UTC, KoffeinKaio commented
nice one, just wanted to suggest adding another func to SAMLSettings as I'm not THAT familiar with PHPUnit. Will add that to my todo list.

2022-05-24 11:13 UTC, blizzz commented
> 



> nice one, just wanted to suggest adding another func to SAMLSettings as I'm not THAT familiar with PHPUnit. Will add that to my todo list.

these tests as they are written are not exactly elegant… but should work til next changes :D

2022-05-24 11:13 UTC, blizzz approved these changes

2022-05-24 11:55 UTC, merged

2022-05-24 11:55 UTC, blizzz commented
thanks for you contribution @KoffeinKaio :coffee: