feat: IdP Post
nextcloud/user_saml pull request #861
Opened 2024-06-28 11:54 UTC by hweihwang

2024-07-02 17:22 UTC, blizzz reviewed
Have not tested yet, looks good on first sight, just two small nitpicks (and knowing about the open questions).

2024-07-02 17:22 UTC, blizzz commented on lib/Controller/SAMLController.php
> +	public function login(int $idp = 1) {
```suggestion
	public function login(int $idp = 1): Http\RedirectResponse|Http\TemplateResponse {
```

2024-07-02 17:22 UTC, blizzz commented on templates/login_post.php
> +		<p>JavaScript is disabled. Click the button below to continue.</p>
Should be translatable. The I18N instance is always available in templates vias `$l`.

```suggestion
		<p><?php p($l->t('JavaScript is disabled. Click the button below to continue.')) ?></p>
```

2024-07-05 09:47 UTC, blizzz requested changes
Please check the `post` if-branch in `login()`.

When modifying this locally and testing with keycloak I receive "We are sorry... Invalid Request". But it could be my Keycloak config needs adjustment, if it supports that.

2024-07-05 09:47 UTC, blizzz commented on templates/login_post.php
> +p($l->t('Please wait while you are redirected to the SSO server.'));
:fire:

2024-07-05 09:47 UTC, blizzz commented on lib/Controller/SAMLController.php
> +				if ($method === 'post') {
`$method` is currently either `"1"` or `"get"`.

2024-07-09 09:13 UTC, blizzz reviewed
Looks good and works :+1: 

Any luck with shibboleth integration tests yet?

2025-05-02 08:50 UTC, blizzz commented
@hweihwang since it is all done, can you do a rebase and perhaps add an `(experimental)` to the settings, and we just merge it?

2025-05-06 15:22 UTC, blizzz reviewed
one question and one suggestion

2025-05-07 07:36 UTC, hweihwang commented on tests/unit/Command/GetMetadataTest.php
> +
Oh that's great, so the CI failed is expected then! Thank you!

2025-05-07 14:34 UTC, blizzz commented on tests/unit/Command/GetMetadataTest.php
> +
It is not expected that CI fails, but it should not be suppressed. Right now it is failing due to rate-limiting when fetching the patch. https://github.com/nextcloud/user_saml/pull/950/commits/d83d1a71e4555295eb6258065e60b2538faad680 fixes this.

2025-05-07 14:38 UTC, blizzz approved these changes

2025-05-07 14:38 UTC, merged